/* topics.js — every shipped question sits on exactly ONE focus row, and every row is one of HER numbered criteria
 * ("Continuous Tests and Exam Focus Points", Science 2 Detailed Content.docx — Module 3: Genetics 1-9, Special Senses 1-13,
 * Reproductive 1-14). Where her quizzes ask something her criteria never name, the row says so (crit 'not in her criteria').
 *
 * HOW. Ordered rules over the stem + the CORRECT answer + matching pairs + blank keys + her model answer (never the distractors:
 * they drag a question onto the wrong row). The FIRST rule that matches wins, so specific rows come before general ones.
 * Rules only PROPOSE; every group was read by eye (21 Sep 2026) and misfits moved with PIN, by question id.
 * The build applies this file, counts each row itself (n · all · pts · qz · saq) and FAILS if a shipped question has no row.
 */
export const RULES = [
  /* ── Special senses first: a colour-blindness question about CONES is vision (SS 2), not inheritance ── */
  ['eye-retina',     /colou?r ?blind\w* .{0,80}(cone|receptor|photorecept)|(cone|receptor|photorecept).{0,80}colou?r ?blind|afterimage|\brods?\b .{0,40}\bcones?\b|photorecept|rhodopsin|fovea|macula|blind spot|optic disc|visual (cortex|pathway)|optic chiasm|bipolar|ganglion cell|scotopic|photopic|night vision/i],
  /* ── Genetics ── */
  ['gen-pedigree',   /pedigree|genogram|\b(I|II|III|IV)-\d\b|queen victoria|individual \d|shaded/i],
  ['gen-karyotype',  /karyotype|non-?disjunction|trisomy|monosomy|aneuploid|down'?s? syndrome|turner|klinefelter|\b4[57] chromosomes|\bXXY\b|\bXO\b|extra chromosome|too (many|few) chromosomes/i],
  ['gen-testing',    /amniocentesis|chorionic villus|\bCVS\b|fetal test|genetic (test|screen|counsel)|prenatal (test|screen|diagnos)|ultrasound scan/i],
  ['gen-therapy',    /gene therapy|genetic engineering|recombinant|\bGMO\b|\bCRISPR\b|clon(e|ing)|stem cells?/i],
  ['gen-mito',       /mitochondrial (dna|inherit)|mitochondria .{0,60}(mother|maternal|inherit)/i],
  ['gen-sexlinked',  /x-?linked|sex-?linked|colou?r ?blind|ha?emophilia|y chromosome|sex chromosomes?|sex determination|carrier (mother|female)/i],
  ['gen-blood',      /blood (type|group)|\bABO\b|multiple alleles|antigen|universal (donor|recipient)|rhesus/i],
  ['gen-patterns',   /co-?dominan|incomplete dominan|polygen|intermediate (phenotype|is expressed)|expressed as an intermediate|continuous (phenotypic )?variation|pink|skin colou?r|sickle|roan/i],
  ['gen-disorders',  /mutation|mutagen|huntington|cystic fibrosis|tay-?sachs|phenylketonuria|\bPKU\b|albinism|marfan|genetic (disease|disorder)|simple recessive traits/i],
  ['gen-crosses',    /punnett|monohybrid|dihybrid|\bF1\b|\bF2\b|genotypic ratio|phenotypic ratio|probabilit|chance (of|that)|what percentage|percent of|offspring|\b(cross|crossed|mated|mates|marries)\b|\b[A-Z][a-z] ?x ?[A-Z][a-z]\b|\b(25|50|75|100) ?%|genotype of the (bull|cow|man|woman|mother|father|parents?)/i],
  ['gen-dna',        /\bDNA\b|\bRNA\b|nucleotide|double helix|chromatin|histone|replicat|mitosis|meiosis|crossing over|homologous|diploid|haploid|zygote|chromatid|centromere|\b(23|46)\b.{0,20}chromosomes|somatic|chromosomes?\b/i],
  ['gen-vocab',      /allele|genotype|phenotype|homozyg|heterozyg|dominant|recessive|\bgenes?\b|locus|trait|heredit|inherit|genom|autosom|variation|freckles|true.?breeding|hybrid/i],
  /* ── Reproductive ── */
  ['repro-terms',    /menarche|menopause|amenorrh|dysmenorrh/i],
  ['repro-female-hormones', /contracepti|the pill|birth control|\bIUD\b|tubal ligation/i],
  ['repro-cycle-uterine', /menstrua|uterine cycle|proliferative|secretory phase|functional layer|basal layer|spiral arter|endometrium (is|thickens|builds|sheds)|shed(ding)? of the endometrium/i],
  ['repro-cycle-ovarian', /ovarian cycle|follicular phase|luteal|\bLH\b|\bFSH\b|lh surge|ovulat|follicle|graafian|corpus luteum|corpus albicans|oogenesis|oogoni|oocyte|polar body|\bovum\b|\bova\b/i],
  ['repro-pregnancy', /fertili[sz]|conce(ive|ption)|zona|implant|placenta|\bhCG\b|human chorionic|pregnan|relaxin|lactat|prolactin|oxytocin|breast|ectopic|infertil|\bIVF\b|blastocyst|embryo|morula|trophoblast|umbilical|labou?r|parturition|twins/i],
  ['repro-female-hormones', /o?estrogen|progesterone|female secondary sex/i],
  ['repro-semen',    /semen|seminal (fluid|vesicle)|prostate|bulbo-?urethral|cowper|sperm count|steril|fructose|prostaglandin|alkalin|vasectomy/i],
  ['repro-erection', /erection|erectile|corpora? cavernos|corpus spongiosum|nitric oxide|viagra|male sexual response|ejaculat/i],
  ['repro-sperm',    /spermato|spermio|sperm|sertoli|leydig|interstitial cells|seminiferous|inhibin|acrosom|flagell|motility/i],
  ['repro-testosterone', /testosterone|androgen|male secondary sex|puberty/i],
  ['repro-male',     /testis|testes|testicle|testicular|scrotum|cremaster|dartos|pampiniform|epididymis|vas deferens|ductus deferens|penis|glans|urethra|male reproductive|circumcis|reproductive products and urine/i],
  ['repro-female',   /ovary|ovaries|fallopian|uterine tube|oviduct|fimbria|infundibulum|uterus|uterine|myometrium|perimetrium|endometri|cervix|cervical|vagina|vulva|labia|clitoris|female reproductive|yeast|pap smear|mammary/i],
  ['repro-male',     /reproductive system|gonad|gamete|sexually transmitted|\bSTI\b/i],
  /* ── the rest of the eye ── */
  ['eye-errors',     /myopi|hyperopi|hypermetropi|emmetropi|presbyopi|astigmat|short-?sighted|long-?sighted|near-?sighted|far-?sighted|diverging lens|converging lens|concave lens|convex lens|corrective|spectacles|eye defects|eye condition/i],
  ['eye-imbalances', /glaucoma|cataract|conjunctivitis|pink ?eye|macular degeneration|intraocular pressure/i],
  ['eye-focus',      /accommodat|ciliary|suspensory|near (vision|object)|far (vision|object)|distant object|close-?up|object comes closer|pupil|radial muscles|circular muscles|sphincter|dilat|constrict|refract|inverted|real image|biconvex|focus/i],
  ['eye-anatomy',    /\beyes?\b|eyeball|cornea|sclera|choroid|conjunctiva|\blens\b|aqueous|vitreous|humou?r|lacrimal|tears?|eyelid|tunic|canal of schlemm|\biris\b|retina/i],
  /* ── the ear ── */
  ['ear-deafness',   /deaf|hearing loss|hearing aid|cochlear implant|otosclerosis|otitis|tinnitus|noise.induced|\bNIHL\b|ear ?wax|cerum|presbycusis|sound shirt|grommet/i],
  ['ear-balance',    /balance|equilibrium|vestibul|semicircular|utricle|saccule|otolith|ampulla|crista|vertigo|motion sickness/i],
  ['ear-hearing',    /cochlea|organ of corti|basilar|tectorial|hair cells?|stereocilia|scala|perilymph|endolymph|round window|tonotopic|transduc|physiology of hearing/i],
  ['ear-anatomy',    /\bears?\b|pinna|auricle|auditory (canal|tube|nerve)|tympan|eardrum|ossicle|malleus|incus|stapes|oval window|eustachian|pharyngotympanic|middle ear|outer ear|inner ear|hearing|vestibulocochlear/i],
  ['taste',          /taste|gustat|papilla|umami/i],
  ['smell',          /smell|olfact|odou?r/i],
  /* ── physics of light and sound ── */
  ['phys-waves',     /sound|decibel|\bdB\b|frequenc|pitch|loudness|amplitude|hertz|\bHz\b|ultrasound|infrasound|doppler|echo|vibrat|longitudinal|compression|rarefaction|vacuum/i],
  ['phys-bend',      /light|wavelength|spectrum|rainbow|prism|colou?rs?|electromagnetic|ultraviolet|infrared|reflect|transparen|opaque|mirror|optical illusion/i],
];
/* moved by hand after reading the groups: question id -> row */
export const PIN = {
  /* released 21 Sep when the image binder learned to read unquoted src and the bare-letter rule was fixed — read by eye like the rest */
  q9b7e52e55b:'gen-crosses', q096557147b:'gen-crosses', qbf650b004d:'gen-crosses', qafbfe87657:'gen-crosses',
  q997d4f4436:'repro-sperm', q82d491b4c0:'eye-anatomy', qf6bbe40991:'repro-cycle-ovarian', qd5ae970dc8:'gen-pedigree', q1b3811c4ef:'ear-anatomy',
  q969c3c85cc:'gen-sexlinked',
  qad2e3f869b:'eye-anatomy',
  q73f30c2a67:'eye-retina',
  qfa89af9f25:'eye-anatomy',
  q3da24a1a85:'eye-anatomy',
  qa5e93ced16:'eye-anatomy',
  qfa2f650482:'eye-anatomy',
  q69016c771a:'ear-balance',
  qf2ae6a15b7:'eye-errors',
  qa7eed3ac3b:'eye-errors',
  qb38324f8e1:'eye-focus',
  q8eaf1e1b17:'eye-focus',
  q83cd61d2d7:'eye-imbalances',
  qcfd00b5c75:'eye-imbalances',
  q555a14ddf8:'phys-bend',
  q6f2eb50185:'phys-bend',
  q15fd69f68b:'phys-bend',
  qfe58e60567:'phys-bend',
  qd992242132:'phys-bend',
  q1a51992224:'phys-bend',
  q54556c18ab:'phys-bend',
  q0b53507b0c:'phys-bend',
  qd96e135cf4:'phys-bend',
  q2ddf9e0576:'phys-bend',
  q70e941c387:'phys-bend',
  qc94d5cff46:'phys-bend',
  qb5d47187a7:'phys-bend',
  qe3e204b22c:'ear-anatomy',
  q5524bb4292:'ear-anatomy',
  qecf2bf30a0:'ear-anatomy',
  q55c7b97606:'ear-hearing',
  qfbcf45ca29:'ear-hearing',
  q41a12e1f9c:'phys-waves',
  qe0e0a2fdb7:'phys-waves',
  q534e4c99e4:'ear-deafness',
  q2fcdaa9e49:'ear-deafness',
  q3ab56ce02a:'ear-deafness',
  qb8321fdbe0:'repro-female',
  q519092544e:'repro-female',
  q745a958361:'repro-female',
  q896ed45268:'repro-female',
  q25927bb9c8:'repro-female',
  q7eec919cbc:'repro-female',
  q0da0fc022e:'repro-female',
  qf2cae28f86:'repro-cycle-ovarian',
  qb77255cdb7:'repro-cycle-ovarian',
  q1e02196c93:'repro-cycle-ovarian',
  q16701ba431:'repro-cycle-ovarian',
  qdab9333ca2:'repro-cycle-ovarian',
  q948a97245c:'repro-cycle-ovarian',
  qccdc39b55d:'repro-sperm',
  q58122e2408:'repro-sperm',
  q463cb2e7bc:'repro-sperm',
  q70fa096ecb:'repro-sperm',
  q20a4aeeaee:'repro-sperm',
  q14e878c37b:'repro-sperm',
  q18cf26e08b:'repro-sperm',
  q0dd7704174:'repro-sperm',
  q865e72d0c2:'repro-sperm',
  q30039ceeaf:'repro-sperm',
  q896b441451:'repro-sperm',
  q3401e33d38:'repro-sperm',
  qe233766bcf:'repro-sperm',
  q3428873f3e:'repro-female-hormones',
  q2363676654:'repro-female-hormones',
  q56de718622:'repro-female-hormones',
  q99dd42a439:'repro-pregnancy',
  q86e6314fe0:'repro-pregnancy',
  qf2fc819f35:'repro-male',
  q6cd0504c7f:'repro-male',
  qe2ee2fd35c:'repro-male',
  q55d365a89c:'repro-male',
  q090f14f81b:'repro-male',
  q3b8e6a6cf6:'repro-male',
  q7108ad86e8:'repro-male',
  q5ae0bc85ae:'repro-male',
  qc81960d3b7:'repro-male',
  qca3e0c0c0f:'repro-male',
  q578b695472:'repro-semen',
  q01d6c80a75:'repro-semen',
  q5a93bb7bd9:'repro-testosterone',
  qd37172e9c2:'repro-testosterone',
  q5f1de75cd5:'gen-vocab',
  q0f58f154ae:'gen-vocab',
  q316970d173:'gen-dna',
  qf2bb3de90f:'gen-pedigree',
  qa2e4edbb5f:'gen-pedigree',
  q425d07a7a7:'gen-pedigree',
  q6b152501ab:'gen-pedigree',
  q26fc21977e:'repro-male',     // 211071 #19 vasectomy (released 21 Sep 2026): every blank is a duct or gland on the sperm's path
  q3dc03a23ff:'gen-pedigree',   // 211091 #19, her question printed on her pedigree figure (released 21 Sep 2026); the rule saw 'inheritance'
  qcda8c1bbce:'gen-crosses',
  q4cf5c0900c:'gen-crosses',
  qb2e41fdc03:'gen-crosses',
  q2d50eafaf8:'gen-crosses',
  q4ce811b8aa:'gen-mito',
  q4b15724ef7:'gen-mito',
  q6888b5cc41:'gen-mito',
  q0998b434b2:'gen-patterns',
  q4b8dbd9a69:'gen-therapy',
};
export function rowOf(q) { if (PIN[q.id]) return PIN[q.id]; const r = RULES.find(([, re]) => re.test(q.t)); return r ? r[0] : null; }
